---
name: "Set up Vagrant"
description: "Set up Vagrant with Libvirt on GitHub Actions"
runs:
  using: "composite"
  steps:
    - id: script
      shell: bash
      run: |
        . /etc/os-release
        if [ "${VERSION_ID}" != "22.04" ]; then
          sudo add-apt-repository --yes ppa:evgeni/vagrant
        fi
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends vagrant vagrant-libvirt libvirt-daemon-system libvirt-daemon qemu-system-x86 qemu-utils dnsmasq
        sudo chmod 666 /var/run/libvirt/libvirt-sock
